version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - echo Installing zip...
      - yum install -y zip

  pre_build:
    commands:
      - echo Cleaning previous builds...
      - mvn clean

  build:
    commands:
      - echo Building the application...
      - mvn package -DskipTests

  post_build:
    commands:
      - echo Preparing deployment artifacts...
      - mkdir deploy
      - cp target/order-demo.jar deploy/
      - cp appspec.yml deploy/
      - cp -r scripts/ deploy/

artifacts:
  base-directory: deploy
  files:
    - appspec.yml
    - order-demo.jar
    - scripts/**/*

