version: 0.2
phases:
  build:
    commands:
      - echo Entered build phase ...
      - mvn clean package
  post_build:
    commands:
      - echo Build completed successfully
      - echo "Copying artifacts..."
      - mkdir -p deploy
      - cp target/order-demo.jar deploy/
      - cp -r scripts deploy/
      - cp appspec.yml deploy/
artifacts:
  base-directory: .
  files:
    - target/order-demo.jar
    - scripts/***
    - appspec.yml
  discard-paths: yes
