version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - mvn -v
  pre_build:
    commands:
      - echo "Cleaning previous builds..."
      - mvn clean
  build:
    commands:
      - echo "Building application without tests..."
      - mvn package -DskipTests
  post_build:
    commands:
      - echo "Preparing deployment package..."
      - mkdir -p deploy
      - cp target/order-demo.jar deploy/
      - cp -r appspec.yml scripts/ deploy/
      - cd deploy && zip -r ../order-demo.zip . && cd ..
artifacts:
  files:
    - order-demo.zip
